# Generated by Django 5.2.3 on 2025-12-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pricedata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sku",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="pricedata",
            constraint=models.UniqueConstraint(
                fields=("sku", "website"), name="unique_sku_website"
            ),
        ),
    ]
