# Generated by Django 5.2.3 on 2025-12-24 21:09

import uuid
from django.db import migrations, models


def populate_api_keys(apps, schema_editor):
    AppUser = apps.get_model("execution", "AppUser")
    for user in AppUser.objects.all():
        if not user.api_key:
            user.api_key = uuid.uuid4()
            user.save(update_fields=["api_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0002_alter_pricedata_unique_together_sku_is_premium_and_more"),
    ]

    operations = [
        # Add the field with default (for new users)
        migrations.AddField(
            model_name="appuser",
            name="api_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        # Populate existing users
        migrations.RunPython(populate_api_keys, reverse_code=migrations.RunPython.noop),
    ]
