# Generated by Django 5.2.3 on 2025-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0002_scrapingresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricedata",
            name="website",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="ScrapingResult",
        ),
        migrations.DeleteModel(
            name="Website",
        ),
    ]
