# Generated by Django 5.2.3 on 2025-12-24 21:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0003_appuser_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="api_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
